### ISSUE TITLE
How can I deploy this library in Expo?

### ISSUE THREAD

**Issue by lnanhkhoa** [Polidea/react-native-ble-plx#172]
Homepage : https://expo.io/
I can't change config in ./ios folder. So I wanna deploy it on iphone.

**Comment by stinodes** [comment]
The easiest route would probably to just use regular react-native, instead of expo.

> Standard Expo projects don’t support custom native code, including third-party libraries which require custom native components. In an Expo project, you only write pure JS. Expo is designed this way on purpose and we think it’s better this way.

**But...**

> However, if you need something very custom—like on-the-fly video processing or low level control over the Bluetooth radio to do a firmware update—we do have early/alpha support for using Expo in native Xcode and Android Studio projects.

So I guess that, if you are really bent on using expo, you could take a look at [this link that their docs include](https://docs.expo.io/versions/latest/guides/expokit.html).

source: https://docs.expo.io/versions/latest/introduction/faq.html#how-do-i-add-custom-native-code-to-my-expo-project
