### ISSUE TITLE
Add BLE actions to new Sniffator

### ISSUE THREAD

**Issue by jerzyKleszcz** [Polidea/react-native-ble-plx#192]
BLE actions have to use Redux middleware framework: redux-saga or redux-thunk.
#189

**Comment by darkrift** [comment]
Do you guys have an idea where complex objects such as Device could be stored while still allowing actions and reducers ? According to good practices, it shouldn't be in the redux store so it allows time travel properties and ease persistence.

Where would you keep a reference to the objects received from startDeviceScan() in order to allow access to it in a reducer ?
