### ISSUE TITLE
Finding only one Device after Scan

### ISSUE THREAD

**Issue by vinipachecov** [Polidea/react-native-ble-plx#219]
Hi there,

No matter how mobile devices there are around with bluetooth on , I only find one after a scan. I've created an app with Kotlin and did the search and it could find all devices available as It was supposed to. Any help is welcome.

Mobile device tested  Moto E
OS: Linux Deepin 15.5
React Project: Native Code
Code of the project: https://github.com/vinipachecov/react-native-bluetooth

Here is the main part of the code:
![image](https://user-images.githubusercontent.com/2838834/35355210-c2ebf92a-0133-11e8-9381-645b9ffb96e6.png)

As you can see it is a very basic react class code just with the functions of the library to scan devices and add to a state and later try to show it.
![image](https://user-images.githubusercontent.com/2838834/35355223-cd743358-0133-11e8-8502-148c72d3fcfa.png)

My render method:
![image](https://user-images.githubusercontent.com/2838834/35355233-d3486416-0133-11e8-8a09-77df9e8d75e4.png)

The result when pressing the button to search devices is like this(console.log):
![image](https://user-images.githubusercontent.com/2838834/35355601-f579ed7e-0134-11e8-87ff-7cad9e70aa00.png)

**Comment by piotrdubiel** [comment]
Hi!
The problem is in the way you're constructing `deviceList` and updating the state. React and React Native require you to use `this.setState` to trigger state update and later re-render as a result. If you use mutating function like `Array.prototype.unshift()` then your array's content will change, but it will not trigger component re-render.

Consider this example
```js

class Test extends Component {
  constructor() {
    super()
    this.state = { list: [] }
  }

  componentWillMount() {
    setInterval(() => {
      // this.state.list.unshift(new Date().getTime()) // No render :(
        this.setState(prevState => ({ // using this.setState will trigger render
          list: [new Date().getTime(), ...prevState.list],
        }))
    }, 1000)
  }

  render() {
    console.log("render")
    return (
      <View>
        <Button onPress={() => this.forceUpdate()} title="Force update"/>
        <Text>The list of length {this.state.list.length}:</Text>
        {this.state.list.map((v, i) => <Text key={i}>{v}</Text>)}
      </View>
    )
  }
}
```
It's pretty similar to what you have now, because it asynchronously "updates" state each second. The problem is, if it calls unshift then only forcing update will show the content of the list.
On the other hand, if the `setState` is used then updates each second with new timestamp.
Generally, the better practice is to follow immutable approach and always returning new object, like in this example with spread operator.

I hope it clarifies things :)

**Comment by vinipachecov** [comment]
Thank you @piotrdubiel. The issue of finding only one value has been solved. Still I couldn't find my Iphone even after refactoring the code.

**Comment by dariuszseweryn** [comment]
Does your iPhone advertise itself?
