### ISSUE TITLE
Cannot install in empty react-native project

### ISSUE THREAD

**Issue by reense** [Polidea/react-native-ble-plx#256]
Hello!

 I just executed `npm install --save react-native-ble-plx` in my project directory, but the dependencies `RxBluetoothKit.framework` and `RxSwift.framework` are not installing, due to an incompatible swift version. 

It tells me that my swift version is to high. What should i do to fix this problem?

[image](https://user-images.githubusercontent.com/3921273/38699036-3a3dae10-3e97-11e8-863b-ca599b440cd6.png)

**Comment by Cierpliwy** [comment]
I think this error is a bit misleading. It only means that due to higher version of your Swift compiler carthage couldn't use prebuild binaries and had to compile them from source. Everything should work just fine.

> What should i do to fix this problem?

You can't really. I will update to High Sierra soon and rebuild dependencies with Swift 4.1.

**Comment by Cierpliwy** [comment]
#243

**Comment by reense** [comment]
@Cierpliwy Great! Thanks for your adequate reaction.

**Comment by 814k31** [comment]
@Cierpliwy whats the purpose of using carthage in this package? Can it be removed?

With the complexity of brew now not allowing sudo and the postinstall.js script failing (#174) it seems more trouble than it's worth

At least I've spent way to much time trying to get around carthage for this package

**Comment by brancooo1** [comment]
@Cierpliwy any news on building dependencies with Swift 4.1 ?
