### ISSUE TITLE
[iOS][0.9.0] Device.onDisconnected() emits nulls

### ISSUE THREAD

**Issue by dariuszseweryn** [Polidea/react-native-ble-plx#265]
When running the below code snippet the error is a `null` instead of `BleError`. It is observed on `iOS` only.
```
  device.onDisconnected((error) => {
    console.log(typeof error); // 'object'
    console.log(error === null); // 'true'
  });
```
On Android the library seems to work just fine.

**Comment by dominikeinkemmer** [comment]
The checks you log are the default javascript behavior it seems (screenshot from chrome console).
![image](https://user-images.githubusercontent.com/18051009/41159641-29e694ac-6b68-11e8-9798-930d60110f92.png)

I assume that the library emits null for the error variable if there is no error during disconnecting. So if you want to check if there was an error and do something with it, you can just check for `if(error)` .

**Comment by dariuszseweryn** [comment]
I have induced disconnection from the outside—I would expect the library to consistently report this situation as an exception (on Android it behaves this way)

**Comment by suark** [comment]
I am also seeing this behavior. 

1. Connect to a BLE device. 
2. Connect to that BLE in our app.
3. Unplug the BLE device.
4. a. On android it will trigger device.onDisconnected with error defined as a BleError.
4. b. On iOS it will trigger device.onDisconnected with the error === null

**Comment by suark** [comment]
@Cierpliwy I feel confused because those docs say "If an error is null, that means the connection was terminated by bleManager.cancelDeviceConnection() call.". 

To me, this implies that a "null" error means an intentional disconnection. If my ble server suddenly loses power, it was not an intentional disconnection. Yet it seems impossible to determine the difference between this and when we purposefully call the function(cancelDeviceConnection()) to manually disconnect from a device. 

Also you mention "On iOS, when connection was terminated by an application error might be set to null." but the docs don't mention any special case for iOS in your link. 
![capture](https://user-images.githubusercontent.com/6233440/46815268-cc57c680-cd37-11e8-8c36-c94e3d58226c.PNG)


To me, the problem is that the behavior is inconsistent between android and iOS. On android I seem to be able to reliably count on have a defined error when the disconnection is caused due to an error, such as suddenly losing connection to a ble server device. But on iOS it seems that it's impossible to distinguish this difference so we are unable to know if our user clicked "disconnect" or the device just disappeared off the face of the earth. 

How are we supposed to detect that we just lost connection to the BLE server device if the device.onDisconnected function is being passed a null error for iOS, but a defined error for android?

**Comment by suark** [comment]
@Cierpliwy Is there any way we could detect this and throw an error so that the behavior is the same for android and ios for react-native users?

**Comment by dennis-b** [comment]
i also seeing same behavior on ios, is there any update on this one?

**Comment by cernadasjuan** [comment]
@suark Thanks, I implemented what do you say and it's working fine

**Comment by suark** [comment]
@cernadasjuan that's awesome. Cheers!
