### ISSUE TITLE
Disconnect events ignored if received before connection succeeds on iOS

### ISSUE THREAD

**Issue by rickgrundy** [Polidea/react-native-ble-plx#331]
When using this library to reconnect to a peripheral in the background when it next comes into range we call `bleManager.connectToDevice` and expect that the promise will eventually either resolve with a connected device, or fail with an error.

On iOS we occasionally see the OS raise a disconnect event *before* it connects to the device when right on the edge of bluetooth signal range . Example snippet from bluetoothd logs:

![ble_early_disconnect](https://user-images.githubusercontent.com/148630/44761807-e83c4a00-ab87-11e8-8934-f1a24979390a.png)

`BleModule.swift#safeConnectToDevice` only starts to monitor the disconnection observable after it is satisfied that a device has connected. This results in the disconnect event being silently ignored - the JS client does not receive an error and is unaware that it needs to retry the `bleManager.connectToDevice` call.

We have field tested a successful workaround by modifying  `BleModule.swift#safeConnectToDevice` to start monitoring disconnections before it calls `connect()` and bail out with `BleError.cancelled()` if we receive a disconnect before the connection attempt finishes. I'll open a PR and link it to this issue, but we're not particularly familiar with reactive Swift and there may be a cleaner way to solve the problem.

Ultimately this feels like an iOS bug but we can't argue with the observed behaviour and supporting this scenario shouldn't do any harm if the "feature" changes in future versions of the OS - it'll just become a no-op.

**Comment by Cierpliwy** [comment]
You spotted that operating system, after `connect()`, called:
`func centralManager(CBCentralManager, didDisconnectPeripheral: CBPeripheral, error: Error?)`

instead of:
`func centralManager(CBCentralManager, didConnect: CBPeripheral)`
or
`func centralManager(CBCentralManager, didFailToConnect: CBPeripheral, error: Error?)`
?

iOS documentation actually guarantees that above functions should be called... If that's not the case, then definitely it's an iOS bug.
