### ISSUE TITLE
My app hang up during bluetooth is turning on by using enable()

### ISSUE THREAD

**Issue by nagaokashi** [Polidea/react-native-ble-plx#428]
Is it possible?
If yes, is there any solution ?

**Comment by Cierpliwy** [comment]
When I was testing this functionality on Android, I didn't spot any problems. Could you fill all the necessary details, so that I can somehow help you to debug the issue? Please check [bug issue template](https://github.com/Polidea/react-native-ble-plx/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to see what information is essential for me.
