### ISSUE TITLE
Sending long data to BLE Device 

### ISSUE THREAD

**Issue by swapniliziss** [Polidea/react-native-ble-plx#581]
I have to send big data (60 bytes)Android, for that I am increasing MTU by using "requestMTUForDevice", but it not increase. Could you help me how i send long data to BLE Device?

**Comment by pstanton** [comment]
chunk your data

**Comment by Cierpliwy** [comment]
Requesting MTU doesn't guarantee to change it. If it returns for example 23, you should as @pstanton said chunk your data. Chunking data is necessary only when using notifications and writes without response. Otherwise, you should be able to write values up to 512 bytes and the LE layer should chunk it for you.

**Comment by rfbezerra** [comment]
I achivied this using the *RxBleConnection.LongWriteOperationBuilder*.
Is there any plan to have an "safeLongWriteCharacteristicForDevice" or anything like that officially?
