### ISSUE TITLE
Connect to a device using its mac address

### ISSUE THREAD

**Issue by tolik85** [Polidea/react-native-ble-plx#689]
Hello!

Can I connect to a device using its mac address only, like in native implementation of this library?
I tried to find my device using BleManager.devices('aa:aa:aa:aa:aa:aa'), but it's returning an empty array.

The goal is to connect to my specific device without making a BLE scan.

Thank you!

**Comment by dariuszseweryn** [comment]
On iOS there is no possibility to get a MAC address of a device. On Android it works if the MAC address is static.

**Comment by RRMoelker** [comment]
Is is required to scan before connecting to the device using its unique id?

And if it is required, is that a hard limitation by the underlying OS or something that can be improved in the library?

p.s. This question seem in line with original issue. If you disagree I'll happily create a new ticket.

**Comment by dariuszseweryn** [comment]
> Is is required to scan before connecting to the device using its unique id?

On iOS it is not required. On Android it is not required if the device is bonded or has been recently connected (and there was no bluetooth adapter powercycle in between) — otherwise YMMV — it is OS bug/limitation. Unfortunately there is no bulletproof way to fix it in library so it is always better to scan on Android before connecting if a not bonded device is used.

**Comment by Datagrdn** [comment]
@dariuszseweryn I see you mention that you can connect to a device with MAC address alone on Android. Can you share how? In the documentation I'm just seeing use of UUID.

Thank you!
